package com.addexstores.enums;

public enum NotificationType {
    ORDER_CONFIRMATION,
    SHIPPING_UPDATE,
    DELIVERY_CONFIRMATION,
    ORDER_CANCELLATION,
    REFUND_CONFIRMATION,
    PROMOTION,
    REVIEW_RESPONSE,
    SYSTEM
}
