-- ============================================================
-- V100: Master categories + sub_categories
-- Categories carry their frontend icons (from legacy V6).
-- No explicit ids; natural keys (slug) drive idempotency.
-- ============================================================

INSERT INTO categories (name, slug, description, image, product_count, icon)
SELECT v.name, v.slug, v.description, v.image, v.product_count, v.icon
FROM (VALUES
    ('Men', 'men', 'Premium men''s fashion featuring tailored suits, casual wear, accessories, and footwear from world-class designers.',
     '/assets/placeholders/men.jpg', 42,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="10" cy="14" r="6"/><path d="M19 5l-5.4 5.4"/><path d="M15 5h4v4"/></svg>'),
    ('Women', 'women', 'Curated women''s luxury collection from haute couture dresses to timeless accessories and exclusive designer pieces.',
     '/assets/placeholders/women.jpg', 38,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="9" r="6"/><path d="M12 15v6"/><path d="M9 21h6"/></svg>'),
    ('Fashion', 'fashion', 'Trendsetting streetwear and contemporary fashion blends from avant-garde designers and luxury labels.',
     '/assets/placeholders/fashion.jpg', 35,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6 4h12l4 7-5 7-7-4-7 4-5-7 4-7z"/></svg>'),
    ('Shoes', 'shoes', 'Exquisite footwear collection from Italian leather loafers to limited-edition sneakers and elegant heels.',
     '/assets/placeholders/shoes.jpg', 28,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 14c.5-1 2-2 5-2 4 0 5 2 8 2 2 0 3.5-1 4-2"/><path d="M3 18c.5-1 2-2 5-2 4 0 5 2 8 2 2 0 3.5-1 4-2"/><path d="M2 22c.5-1 2-2 5-2 4 0 5 2 8 2 2 0 3.5-1 4-2"/><path d="M4 10c.5-1 2-2 5-2 4 0 5 2 8 2 2 0 3.5-1 4-2"/></svg>'),
    ('Watches', 'watches', 'Haute horlogerie timepieces from Swiss masters including Rolex, Patek Philippe, Audemars Piguet and more.',
     '/assets/placeholders/watches.jpg', 22,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="8"/><path d="M12 8v4l2 2"/><path d="M10 2h4"/><path d="M11 22h2"/></svg>'),
    ('Bags', 'bags', 'Luxury handbags and accessories from Hermès, Louis Vuitton, Chanel and other iconic fashion houses.',
     '/assets/placeholders/bags.jpg', 26,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 8h16l-1.5 12H5.5L4 8z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></svg>'),
    ('Perfumes', 'perfumes', 'Artisan-crafted fragrances from renowned perfumers featuring rare ingredients and exquisite blends.',
     '/assets/placeholders/perfumes.jpg', 20,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v6"/><path d="M8 8h8v2a6 6 0 0 1-6 6h-4a2 2 0 0 1-2-2v-2a4 4 0 0 1 4-4z"/><path d="M8 16v4a2 2 0 0 0 2 2h4a2 2 0 0 0 2-2v-4"/></svg>'),
    ('Beauty', 'beauty', 'Premium beauty and skincare essentials from La Mer, Sisley, and other luxury cosmetic houses.',
     '/assets/placeholders/beauty.jpg', 18,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="4"/><path d="M8 22v-4a4 4 0 0 1 8 0v4"/><path d="M4 12v10"/><path d="M20 12v10"/></svg>'),
    ('Makeup', 'makeup', 'Professional-grade makeup collections from Tom Ford, Charlotte Tilbury, and Dior Beauty.',
     '/assets/placeholders/makeup.jpg', 15,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 2L6 14l4 4L22 6l-4-4z"/><path d="M10 14l-4 4"/><path d="M6 18l-2 4 4-2"/><circle cx="16" cy="8" r="1"/></svg>'),
    ('Skincare', 'skincare', 'Advanced clinical skincare featuring serums, moisturizers, and treatments from La Prairie and Dr. Barbara Sturm.',
     '/assets/placeholders/skincare.jpg', 16,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2a3 3 0 0 0-3 3v1h6V5a3 3 0 0 0-3-3z"/><path d="M12 6v8"/><path d="M8 14h8a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2z"/></svg>'),
    ('Jewelry', 'jewelry', 'Fine jewelry collections from Cartier, Tiffany & Co., Van Cleef & Arpels with diamonds and precious gemstones.',
     '/assets/placeholders/jewelry.jpg', 24,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2l3 5-5 5 3 5-3 5"/><path d="M2 12h8"/><path d="M14 12h8"/><circle cx="12" cy="7" r="1"/><circle cx="12" cy="17" r="1"/></svg>'),
    ('Sports', 'sports', 'Premium sportswear and equipment from Nike, Adidas, and performance luxury brands.',
     '/assets/placeholders/sports.jpg', 14,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a15 15 0 0 0 0 20 15 15 0 0 0 0-20z"/><path d="M2 12h20"/></svg>'),
    ('Electronics', 'electronics', 'Cutting-edge luxury electronics from Bang & Olufsen, Apple, and high-end audio brands.',
     '/assets/placeholders/electronics.jpg', 12,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><path d="M8 6h8"/><path d="M12 18h.01"/></svg>'),
    ('Travel Accessories', 'travel-accessories', 'Refined travel essentials from Rimowa, Tumi, and Bric''s for the discerning global traveler.',
     '/assets/placeholders/travel.jpg', 10,
     '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7h18v14H3z"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><path d="M12 12v4"/><path d="M10 14h4"/></svg>')
) AS v(name, slug, description, image, product_count, icon)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- Sub-categories resolved by category slug (id-free)
-- ============================================================

INSERT INTO sub_categories (name, slug, product_count, category_id)
SELECT v.name, v.slug, v.product_count, c.id
FROM (VALUES
    ('T-Shirts',      't-shirts',       5,  'men'),
    ('Shirts',        'shirts',         5,  'men'),
    ('Jeans',         'jeans',          4,  'men'),
    ('Hoodies',       'hoodies',        4,  'men'),
    ('Jackets',       'jackets',        4,  'men'),
    ('Sneakers',      'sneakers',       5,  'men'),
    ('Formal Shoes',  'formal-shoes',   4,  'men'),
    ('Watches',       'watches',        4,  'men'),
    ('Wallets',       'wallets',        3,  'men'),
    ('Accessories',   'accessories',    4,  'men'),
    ('Dresses',       'dresses',        6,  'women'),
    ('Tops',          'tops',           5,  'women'),
    ('Jeans',         'jeans',          4,  'women'),
    ('Handbags',      'handbags',       5,  'women'),
    ('Heels',         'heels',          4,  'women'),
    ('Makeup',        'makeup',         5,  'women'),
    ('Jewelry',       'jewelry',        4,  'women'),
    ('Skincare',      'skincare',       5,  'women'),
    ('T-Shirts',      't-shirts',       6,  'fashion'),
    ('Shirts',        'shirts',         5,  'fashion'),
    ('Jeans',         'jeans',          5,  'fashion'),
    ('Hoodies',       'hoodies',        4,  'fashion'),
    ('Jackets',       'jackets',        4,  'fashion'),
    ('Shoes',         'shoes',          6,  'fashion'),
    ('Accessories',   'accessories',    5,  'fashion'),
    ('Sneakers',      'sneakers',       7,  'shoes'),
    ('Running Shoes', 'running-shoes',  6,  'shoes'),
    ('Formal Shoes',  'formal-shoes',   5,  'shoes'),
    ('Sandals',       'sandals',        4,  'shoes'),
    ('Sports Shoes',  'sports-shoes',   6,  'shoes'),
    ('Luxury Watches','luxury-watches', 9,  'watches'),
    ('Smart Watches', 'smart-watches',  7,  'watches'),
    ('Sports Watches','sports-watches', 6,  'watches'),
    ('Backpacks',     'backpacks',      7,  'bags'),
    ('Handbags',      'handbags',       8,  'bags'),
    ('Laptop Bags',   'laptop-bags',    5,  'bags'),
    ('Travel Bags',   'travel-bags',    6,  'bags'),
    ('Men Perfumes',  'men-perfumes',   6,  'perfumes'),
    ('Women Perfumes','women-perfumes', 6,  'perfumes'),
    ('Luxury Fragrances','luxury-fragrances',5,'perfumes'),
    ('Body Sprays',   'body-sprays',    3,  'perfumes'),
    ('Lipsticks',     'lipsticks',      3,  'beauty'),
    ('Foundation',    'foundation',     3,  'beauty'),
    ('Face Wash',     'face-wash',      3,  'beauty'),
    ('Serum',         'serum',          3,  'beauty'),
    ('Perfumes',      'perfumes',       3,  'beauty'),
    ('Hair Care',     'hair-care',      2,  'beauty'),
    ('Skin Care',     'skin-care',      1,  'beauty'),
    ('Lipsticks',     'lipsticks',      3,  'makeup'),
    ('Brushes',       'brushes',        3,  'makeup'),
    ('Foundation',    'foundation',     3,  'makeup'),
    ('Kits',          'kits',           3,  'makeup'),
    ('Eye Makeup',    'eye-makeup',     3,  'makeup'),
    ('Face Wash',     'face-wash',      4,  'skincare'),
    ('Serums',        'serums',         4,  'skincare'),
    ('Moisturizers',  'moisturizers',   3,  'skincare'),
    ('Sunscreen',     'sunscreen',      3,  'skincare'),
    ('Masks',         'masks',          2,  'skincare'),
    ('Rings',         'rings',          7,  'jewelry'),
    ('Bracelets',     'bracelets',      6,  'jewelry'),
    ('Necklaces',     'necklaces',      6,  'jewelry'),
    ('Earrings',      'earrings',       5,  'jewelry'),
    ('Gym Bags',      'gym-bags',       3,  'sports'),
    ('Dumbbells',     'dumbbells',      3,  'sports'),
    ('Water Bottles', 'water-bottles',  2,  'sports'),
    ('Sports Shoes',  'sports-shoes',   4,  'sports'),
    ('Accessories',   'accessories',    2,  'sports'),
    ('Smartphones',   'smartphones',    3,  'electronics'),
    ('Earbuds',       'earbuds',        3,  'electronics'),
    ('Smart Watches', 'smart-watches',  2,  'electronics'),
    ('Chargers',      'chargers',       2,  'electronics'),
    ('Accessories',   'accessories',    2,  'electronics'),
    ('Backpacks',     'backpacks',      2,  'travel-accessories'),
    ('Luggage',       'luggage',        3,  'travel-accessories'),
    ('Passport Holders','passport-holders',2,'travel-accessories'),
    ('Travel Pillows','travel-pillows', 1,  'travel-accessories'),
    ('Travel Organizers','travel-organizers',2,'travel-accessories')
) AS v(name, slug, product_count, category_slug)
JOIN categories c ON c.slug = v.category_slug
ON CONFLICT (slug, category_id) DO NOTHING;
